### ISSUE TITLE
Callable Middleware\Authentication does not exist

### ISSUE THREAD

**Issue by mapicard** [dmorawetz/oauth2-server-example#1]
I downloaded your project and ran `"composer update"`. 
But it won't run and gives the following Slim error, like it doesn't find the Authentication middleware.

**Slim Application Error**
The application could not run because of the following error:

Details
Type: RuntimeException
Code: 0
Message: Callable Middleware\Authentication does not exist
File: /vagrant/project/vendor/slim/slim/Slim/CallableResolver.php
Line: 147
**Trace**
```
#0 /vagrant/project/vendor/slim/slim/Slim/CallableResolver.php(101): Slim\CallableResolver->resolveSlimNotation()
#1 /vagrant/project/vendor/slim/slim/Slim/CallableResolver.php(79): Slim\CallableResolver->resolveByPredicate()
#2 /vagrant/project/vendor/slim/slim/Slim/MiddlewareDispatcher.php(208): Slim\CallableResolver->resolveMiddleware()
#3 /vagrant/project/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle()
#4 /vagrant/project/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#5 /vagrant/project/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#6 /vagrant/project/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#7 /vagrant/project/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Slim\Routing\RouteRunner->handle()
#8 /vagrant/project/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#9 /vagrant/project/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle()
#10 /vagrant/project/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#11 /vagrant/project/vendor/slim/twig-view/src/TwigMiddleware.php(125): class@anonymous->handle()
#12 /vagrant/project/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Views\TwigMiddleware->process()
#13 /vagrant/project/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle()
#14 /vagrant/project/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#15 /vagrant/project/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#16 /vagrant/project/public/index.php(26): Slim\App->run()
#17 {main}
```

**Comment by dmorawetz** [comment]
I'll take a look at it on the weekend and come back to you

**Comment by dmorawetz** [comment]
Sorry for the delay. I could not reproduce your bug. Can you provide a fork repository with a docker-compose.yml, that produces your error?

**Comment by mapicard** [comment]
No problem for the delay. I don't know how I can produce a repo with docker-compose.... but I just re-created the problem in less than 10minutes. Here are my steps:
 - created new project directory xyz
 - downloaded your git.zip and extracted it to project directory xyz
 - cd src/config
 - openssl genrsa -out private.key 2048
 - openssl rsa -in private.key -pubout -out public.key
 - composer upgrade
 - open browser to http://localhost/hello/xyz 
 - then I got the above Slim Error 
 - when I visit http://localhost/, i get the same error but for the HomeController
 - `Message: Callable Controllers\HomeController does not exist`
 - visiting /login complains about the LoginController
 - `Message: Callable Controllers\LoginController does not exist`
 - and so on
 - but visiting unknown routes gives proper `404 Not found`


I'd like to have this server-example working since i need to really understand the oauth-pkce-flow. There's a lot of documentation on the PKCE flow but I couldn't find something that puts all the pieces together for a mobile API client to access an API server. Like how do we protect the API server, is anyone allowed to post to api/authorize, etc.... so many questions.... thanks

**Comment by prdsjawe** [comment]
You still have the error? What I did is this:

- go to composer.json, you'll see 
"autoload": {
    "psr-4": {
      "__your_file_name__\\": "src/"
    }
  }
change file name to "App\\":"src/"

- then change all namespaces to App\__namespace__ of all controller files, entity files, middleware and repository files,  
e.g. namespace App\Controllers

- then change all usages of Controllers in routes.php to App\Controllers
e.g. use App\Controllers\HomeController

- then in terminal: composer update

It worked for me!

**Comment by mapicard** [comment]
@prdsjawe thanks a lot. This works for me too.
